### ISSUE TITLE
Test et Validation des Dashboards

### ISSUE THREAD

**Issue by Samy-cho** [Samy-cho/Projet-technique-G8#7]
Description: Tester les visualisations et les tableaux de bord, valider l'exactitude des données et des visualisations, ajuster si nécessaire.

**Comment by ju-hic** [comment]
[dashboard_projettechnique_Gr8_dataBrut.pdf](https://github.com/user-attachments/files/15805593/dashboard_projettechnique_Gr8_dataBrut.pdf)





un dashboard orienté sur chaque animé en fonction de 3 indicateurs : 

- somme des votes, 
- moyenne des score,
- moyenne de la popularité

un dashboard orienté l'année de démarrage des animés en fonction des indicateurs : 

- somme des épisodes,
- somme des votes, 
- moyenne des score,
- moyenne de la popularité,
- moyenne global des scores et de popularité

un dashboard orienté les mangas et notamment leur auteur via les indicateurs : 

- somme des chapitre,
- moyenne des votes, 
- moyenne de la popularité par status,
- moyenne de la popularité par auteurs,
- moyenne global des scores et de popularit
